### ISSUE TITLE
Cannot find module '.enum_manifest.json'

### ISSUE THREAD

**Issue by frontendlead** [dooboolab/dooboo-frontend-ts#84]
Cloned, ran "yarn" then "yarn start"

ERROR in ./src/App.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: src\App.tsx: Cannot find module '.enum_manifest.json'
Require stack:
- node_modules\babel-plugin-fbt\index.js

**Comment by timtruston** [comment]
Yarn test

Test Suites: 6 failed, 6 total
Tests:       0 total
Snapshots:   0 total
Time:        35.844 s
Ran all test suites.

**Comment by 0916dhkim** [comment]
@timtruston Please run `yarn fbt-all` before running `yarn start`. `.enum_manifest.json` is a file required to process fbt translations.
